version: '2.0'
services:
  odoo12_A:
    image: odoo:12.0
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo12/addons:/mnt/extra-addons
      - ./odoo12/etc:/etc/odoo
      - ./odoo12/data:/var/lib/odoo
  odoo12_B:
    image: odoo:12.0
    restart: always
    depends_on:
      - db
    ports:
      - "8071:8069"
    volumes:
      - ./odoo12/addons:/mnt/extra-addons
      - ./odoo12/etc:/etc/odoo
      - ./odoo12/data:/var/lib/odoo
  db:
    image: postgres:10
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  nginx:
    restart: always
    image: nginx
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./www:/var/www
    depends_on:
      - odoo12_A
      - odoo12_B